# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-fd7093ae-e53c-4197-b82a-f791ccb1fda9";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-fd7093ae-e53c-4197-b82a-f791ccb1fda9".device = "/dev/disk/by-uuid/fd7093ae-e53c-4197-b82a-f791ccb1fda9";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/7245-CB4C";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-c2511787-cc49-4a3e-817c-435b40cdbc73"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
